export const textContent = {
  ko: {
    home: {
      heroTitle: 'HYBLOCK',
      heroEyebrow: 'Hanyang Blockchain Academic Club',
      heroDescription: '한양대학교 블록체인 학술 동아리 HYBLOCK은 연구, 개발, 세미나를 통해 Web3를 깊이 있게 탐구하는 커뮤니티입니다.',
      heroCtaIntro: 'HYBLOCK 소개',
      heroCtaAttendance: '출석하기',
      heroCtaApply: '지원하기',
      aboutUsTitle: 'About Us',
      aboutUsSubtitle: 'The Society Blueprint',
      aboutUsVision: '하이블록은 Web3 시대를 배경으로 블록체인이 주도할 새로운 환경을 인식하고, 그 변화의 흐름을 이끌 통찰을 공유하는 모임입니다.',
      latestNoticesTitle: 'Latest Notices',
      latestNoticesCta: '전체 공지 보기',
      pastActivitiesEyebrow: 'Our Archive',
      pastActivitiesTitle: 'Activities',
      pastActivitiesDescription: '세미나, 해커톤, 외부 교류까지 HYBLOCK이 쌓아온 활동을 한눈에 볼 수 있습니다.',
      pastActivitiesEmpty: '아직 표시할 활동 기록이 없습니다.',
      pastActivitiesCta: '전체 활동 보기',
    },
    activities: {
      title: 'Activities',
      intro: '함께 배우고 성장하는 HYBLOCK의 다양한 활동 기록입니다.',
    },
    notices: {
      title: 'Notices',
      description: 'HYBLOCK 학술회의 주요 소식과 공지사항을 확인하세요. 운영, 학술, 이벤트 공지를 확인할 수 있습니다.',
    },
    bylaws: {
      title: '회칙',
      intro: 'Beyond the Chain, Higher Block',
      updatedAt: '최근 업데이트: 2024년 1월',
      closingNote: '본 페이지의 회칙은 HYBLOCK의 운영 기준과 회원 활동 원칙을 정리한 내용입니다.',
    },
    attendance: {
      description: '진행 중인 세션을 확인하고 QR 또는 수동 입력으로 출석을 완료할 수 있습니다.',
      liveSessionLabel: 'Live Session',
      liveSessionFallback: '진행 중인 세션 없음',
      liveSessionDescription: '현재 활성 세션만 출석 처리할 수 있습니다. 운영진이 세션을 열면 아래 입력 폼이 즉시 활성화됩니다.',
      manualCheckInLabel: 'Manual Check-In',
      manualCheckInTitle: '수동 출석',
      activeStatusHint: '지금 출석 가능',
      pendingStatusHint: '오픈 전',
    },
    auth: {
      loginCta: '로그인',
      signupCta: '회원가입',
      noAccountPrefix: '계정이 없다면 ',
      hasAccountPrefix: '이미 가입했다면 ',
      walletLoginMissingProjectId: '`NEXT_PUBLIC_REOWN_PROJECT_ID`를 설정해야 WalletConnect 모달이 동작합니다.',
      walletLinkMissingProjectId: '`NEXT_PUBLIC_REOWN_PROJECT_ID`를 설정해야 WalletConnect 모달이 동작합니다.',
    },
    walletLink: {
      currentAccountLabel: '현재 계정',
      loadingUser: '계정 확인 중',
      emptyLinkedWallet: '없음',
      loginRequired: '먼저 로그인하세요.',
      stepsLabel: '단계',
      connectedWalletLabel: '연결된 지갑',
      unknownNetwork: '알 수 없음',
    },
    footer: {
      copyright: '© 2026 HYBLOCK Academic Club. All rights reserved.',
      policy: '개인정보처리방침',
      terms: '이용약관',
    }
  },
  en: {
    home: {
      heroTitle: 'HYBLOCK',
      heroEyebrow: 'Hanyang Blockchain Academic Club',
      heroDescription: 'HYBLOCK is Hanyang University\'s premier blockchain academic club, deeply exploring Web3 through research, development, and seminars.',
      heroCtaIntro: 'About HYBLOCK',
      heroCtaAttendance: 'Check-In',
      heroCtaApply: 'Apply Now',
      aboutUsTitle: 'About Us',
      aboutUsSubtitle: 'The Society Blueprint',
      aboutUsVision: 'HYBLOCK is a community that recognizes the new environment driven by blockchain in the Web3 era and shares insights to lead that change.',
      latestNoticesTitle: 'Latest Notices',
      latestNoticesCta: 'View All Archives',
      pastActivitiesEyebrow: 'Our Archive',
      pastActivitiesTitle: 'Activities',
      pastActivitiesDescription: 'A glance at HYBLOCK\'s accumulated activities, from seminars and hackathons to external networking.',
      pastActivitiesEmpty: 'No activity records to display yet.',
      pastActivitiesCta: 'View All Activities',
    },
    activities: {
      title: 'Activities',
      intro: 'A record of HYBLOCK\'s diverse activities where we learn and grow together.',
    },
    notices: {
      title: 'Notices',
      description: 'Check out the major news and announcements from HYBLOCK. You can find operational, academic, and event notices.',
    },
    bylaws: {
      title: 'Bylaws',
      intro: 'Beyond the Chain, Higher Block',
      updatedAt: 'Last Updated: January 2024',
      closingNote: 'The bylaws on this page summarize HYBLOCK\'s operational standards and member activity principles.',
    },
    attendance: {
      description: 'Check ongoing sessions and complete attendance via QR or manual entry.',
      liveSessionLabel: 'Live Session',
      liveSessionFallback: 'No live sessions',
      liveSessionDescription: 'Only active sessions can be checked in. The form will activate once an admin opens a session.',
      manualCheckInLabel: 'Manual Check-In',
      manualCheckInTitle: 'Manual Check-In',
      activeStatusHint: 'Available Now',
      pendingStatusHint: 'Before Opening',
    },
    auth: {
      loginCta: 'Login',
      signupCta: 'Sign Up',
      noAccountPrefix: "Don't have an account? ",
      hasAccountPrefix: 'Already have an account? ',
      walletLoginMissingProjectId: 'Set `NEXT_PUBLIC_REOWN_PROJECT_ID` for WalletConnect modal.',
      walletLinkMissingProjectId: 'Set `NEXT_PUBLIC_REOWN_PROJECT_ID` for WalletConnect modal.',
    },
    walletLink: {
      currentAccountLabel: 'Current Account',
      loadingUser: 'Checking account',
      emptyLinkedWallet: 'None',
      loginRequired: 'Please login first.',
      stepsLabel: 'Step',
      connectedWalletLabel: 'Connected Wallet',
      unknownNetwork: 'Unknown',
    },
    footer: {
      copyright: '© 2026 HYBLOCK Academic Club. All rights reserved.',
      policy: 'Privacy Policy',
      terms: 'Terms of Service',
    }
  }
} as const;
