'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useMemo, useState } from 'react';
import type { ApplicantListItem } from '@/lib/recruitment-admin';

const statusLabels: Record<string,string> = { submitted:'접수', document_review:'서류 평가 중', document_passed:'서류 합격', document_rejected:'서류 불합격', interview:'면접', final_passed:'최종 합격', final_rejected:'최종 불합격' };

export default function ApplicantTable({ applicants, sortLinks }: { applicants: ApplicantListItem[]; sortLinks: Record<string,string> }) {
  const router=useRouter();const[selected,setSelected]=useState<string[]>([]);const[status,setStatus]=useState('');const[note,setNote]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  const selectableIds=useMemo(()=>applicants.slice(0,200).map(item=>item.id),[applicants]);const allSelected=selectableIds.length>0&&selected.length===selectableIds.length;const selectedSet=useMemo(()=>new Set(selected),[selected]);
  function toggleAll(){setSelected(allSelected?[]:selectableIds);}function toggle(id:string){setSelected(selectedSet.has(id)?selected.filter(value=>value!==id):selected.length<200?[...selected,id]:selected);}
  async function applyStatus(){if(!selected.length||!status)return;if(!confirm(`선택한 ${selected.length}명의 상태를 '${statusLabels[status]}'(으)로 변경할까요?`))return;setBusy(true);setMessage('');const response=await fetch('/api/admin/recruitment/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationIds:selected,status,note})});const result=await response.json();if(response.ok){setMessage(`${result.updated}명의 상태를 변경했습니다.`);setSelected([]);setNote('');router.refresh();}else setMessage(result.error??'상태 변경에 실패했습니다.');setBusy(false);}
  return <><div className="mt-6 flex flex-col gap-3 rounded-xl border border-monolith-outline-variant bg-monolith-surface-low p-4 lg:flex-row lg:items-center"><strong className="text-sm whitespace-nowrap">{selected.length}명 선택</strong><select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 rounded-lg border border-monolith-outline-variant bg-white px-3 text-sm"><option value="">변경할 상태 선택</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder="변경 사유 (선택)" className="min-h-11 min-w-0 flex-1 rounded-lg border border-monolith-outline-variant bg-white px-3 text-sm"/><button disabled={busy||!selected.length||!status} onClick={applyStatus} className="min-h-11 rounded-lg bg-monolith-primary px-5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">일괄 변경</button>{message&&<span className="text-xs font-bold text-monolith-on-surface-muted">{message}</span>}</div>
  <div className="mt-4 overflow-x-auto rounded-xl border border-monolith-outline-variant"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-monolith-primary-container text-white"><tr><th className="w-12 px-4 py-3"><input aria-label="현재 목록 전체 선택" type="checkbox" checked={allSelected} onChange={toggleAll}/></th><th className="px-4 py-3">이름</th><th className="px-4 py-3">소속</th><th className="px-4 py-3"><Link href={sortLinks.birthYear}>출생연도 ↕</Link></th><th className="px-4 py-3">분야</th><th className="px-4 py-3">상태</th><th className="px-4 py-3 text-right"><Link href={sortLinks.documentScore}>지원서 점수 ↕</Link></th><th className="px-4 py-3 text-right"><Link href={sortLinks.interviewScore}>면접 점수 ↕</Link></th><th className="px-4 py-3"><Link href={sortLinks.submittedAt}>접수일 ↕</Link></th></tr></thead><tbody>{applicants.map(item=><tr key={item.id} className={`border-t border-monolith-outline-variant hover:bg-monolith-surface-low ${selectedSet.has(item.id)?'bg-monolith-primary-fixed/40':''}`}><td className="px-4 py-4"><input aria-label={`${item.name} 선택`} type="checkbox" checked={selectedSet.has(item.id)} onChange={()=>toggle(item.id)}/></td><td className="p-0"><Link className="block px-4 py-4 font-bold text-monolith-primary" href={`/admin/recruitment/${item.id}`}>{item.name}</Link></td><td className="px-4 py-4">{item.university}<span className="block text-xs text-monolith-on-surface-muted">{item.major}</span></td><td className="px-4 py-4">{item.birthYear}</td><td className="px-4 py-4">{item.track}</td><td className="px-4 py-4">{statusLabels[item.status]??item.status}</td><td className="px-4 py-4 text-right tabular-nums">{item.documentScore??'-'}</td><td className="px-4 py-4 text-right tabular-nums">{item.interviewScore??'-'}</td><td className="px-4 py-4">{new Intl.DateTimeFormat('ko-KR').format(new Date(item.submittedAt))}</td></tr>)}</tbody></table>{!applicants.length&&<div className="p-12 text-center text-monolith-on-surface-muted">조건에 맞는 지원자가 없습니다.</div>}</div></>;
}
