'use client';

import { useState } from 'react';

type Item = { id: string; prompt: string; maxScore: number; score?: number; comment?: string };
export default function EvaluationForm({ applicationId, kind, items, completed, globallyFinalized, isEvaluator }: { applicationId: string; kind: 'document'|'interview'; items: Item[]; completed: boolean; globallyFinalized: boolean; isEvaluator: boolean }) {
  const [values,setValues]=useState<Record<string,{score:string;comment:string}>>(()=>Object.fromEntries(items.map(item=>[item.id,{score:item.score == null?'':String(item.score),comment:item.comment??''}])));const[busy,setBusy]=useState(false);const[done,setDone]=useState(completed);const[message,setMessage]=useState('');
  const locked=done||globallyFinalized||!isEvaluator;
  async function save(finalize:boolean){if(finalize&&!confirm('평가를 확정하면 점수와 코멘트를 수정할 수 없습니다. 확정할까요?'))return;const payload=items.map(item=>({itemId:item.id,score:Number(values[item.id]?.score),comment:values[item.id]?.comment}));if(payload.some((item,index)=>!Number.isFinite(item.score)||item.score<0||item.score>items[index].maxScore)){setMessage('모든 점수를 배점 범위 안에서 입력해 주세요.');return;}setBusy(true);setMessage('');const response=await fetch('/api/admin/recruitment/evaluations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId,kind,items:payload,finalize})});const result=await response.json();if(response.ok){setMessage(finalize?'평가를 확정했습니다.':'임시 저장했습니다.');if(finalize)setDone(true);}else setMessage(result.error);setBusy(false);}
  return <section className="rounded-xl bg-monolith-surface-low p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-black">{kind==='document'?'내 지원서 평가':'내 면접 평가'}</h3><p className="mt-1 text-sm text-monolith-on-surface-muted">코멘트는 선택이며 점수는 필수입니다.</p></div><span className="rounded-full bg-monolith-secondary-container px-3 py-1 text-xs font-bold text-monolith-primary">{done||globallyFinalized?'확정됨':isEvaluator?'평가 중':'평가자 아님'}</span></div>{items.length===0?<p className="mt-5 text-sm text-monolith-on-surface-muted">수동 평가 문항이 없습니다. 평가 완료 여부만 확정해 주세요.</p>:<div className="mt-5 space-y-4">{items.map((item,index)=><div key={item.id} className="rounded-lg border border-monolith-outline-variant bg-white p-4"><label className="text-sm font-bold">{index+1}. {item.prompt}<span className="mt-1 block text-xs font-normal text-monolith-on-surface-muted">최대 {item.maxScore}점</span><input disabled={locked} value={values[item.id]?.score??''} onChange={e=>setValues({...values,[item.id]:{...values[item.id],score:e.target.value}})} className="mt-3 min-h-11 w-full rounded-lg border border-monolith-outline-variant px-3 disabled:bg-monolith-surface-container" type="number" min="0" max={item.maxScore} step="0.01" placeholder="점수" required/></label><textarea disabled={locked} value={values[item.id]?.comment??''} onChange={e=>setValues({...values,[item.id]:{...values[item.id],comment:e.target.value}})} maxLength={4000} className="mt-3 min-h-20 w-full resize-y rounded-lg border border-monolith-outline-variant p-3 text-sm disabled:bg-monolith-surface-container" placeholder="관리자 코멘트 (선택)"/></div>)}</div>}{message&&<p className="mt-4 text-sm font-bold">{message}</p>}{!locked&&<div className="mt-5 flex justify-end gap-2">{items.length>0&&<button disabled={busy} onClick={()=>save(false)} className="min-h-11 rounded-lg bg-monolith-surface-container px-4 text-sm font-bold">임시 저장</button>}<button disabled={busy} onClick={()=>save(true)} className="min-h-11 rounded-lg bg-monolith-primary px-4 text-sm font-bold text-white">평가 확정</button></div>}</section>;
}
