'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';

type Campaign = { id: string; title: string; cohort: number; status: string; application_open_at: string; application_close_at: string };
type RecruitmentFormData = { campaign: Campaign; questions: any[]; interviews: any[]; evaluatorIds: number[] };
const field = 'min-h-11 w-full rounded-lg border border-monolith-outline-variant bg-white px-3 py-2 text-sm outline-none focus:border-monolith-primary focus:ring-3 focus:ring-blue-100';
const statusLabel: Record<string,string> = { draft: '초안', open: '접수 중', closed: '접수 마감', selection_complete: '선발 완료', archived: '보관' };
function toLocalDateTime(value:string){const date=new Date(value);const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}

export default function RecruitmentSettings({ initialCampaigns, admins }: { initialCampaigns: Campaign[]; admins: Array<{ id: number; name: string; cohort: number; affiliation: string }> }) {
  const [campaigns, setCampaigns] = useState(initialCampaigns); const [selectedId, setSelectedId] = useState(initialCampaigns[0]?.id ?? '');
  const [data, setData] = useState<RecruitmentFormData | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function load(id = selectedId) { if (!id) { setData(null); return; } const response = await fetch(`/api/admin/recruitment/campaigns/${id}/form`); const result = await response.json(); if (response.ok) setData(result); else setMessage(result.error); }
  useEffect(() => { void load(selectedId); }, [selectedId]);
  async function createCampaign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement=event.currentTarget;setBusy(true);setMessage('');try{const form=new window.FormData(formElement);const response=await fetch('/api/admin/recruitment/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:form.get('title'),cohort:Number(form.get('cohort')),openAt:new Date(String(form.get('openAt'))).toISOString(),closeAt:new Date(String(form.get('closeAt'))).toISOString()})});const result=await response.json();if(!response.ok)throw new Error(result.error);const list=await fetch('/api/admin/recruitment/campaigns').then(r=>r.json());setCampaigns(list.campaigns);setSelectedId(result.campaignId);formElement.reset();}catch(error){setMessage(error instanceof Error?error.message:'모집 생성에 실패했습니다.');}finally{setBusy(false);}}
  async function addQuestion(event: FormEvent<HTMLFormElement>) { event.preventDefault();if(!selectedId)return;const formElement=event.currentTarget;setBusy(true);setMessage('');try{const form=new window.FormData(formElement);const type=String(form.get('type'));const labels=String(form.get('options')??'').split('\n').map(v=>v.trim()).filter(Boolean);const scores=String(form.get('scores')??'').split('\n');const body={kind:'application',type,prompt:form.get('prompt'),description:form.get('description'),required:form.get('required')==='on',maxScore:Number(form.get('maxScore')),scoringMode:form.get('scoringMode'),minLength:form.get('minLength'),maxLength:form.get('maxLength'),sortOrder:data?.questions.length??0,options:labels.map((label,index)=>({label,score:Number(scores[index]??0)}))};const response=await fetch(`/api/admin/recruitment/campaigns/${selectedId}/form`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);formElement.reset();await load();}catch(error){setMessage(error instanceof Error?error.message:'지원서 문항 생성에 실패했습니다.');}finally{setBusy(false);}}
  async function addInterview(event: FormEvent<HTMLFormElement>) { event.preventDefault();const formElement=event.currentTarget;setBusy(true);setMessage('');try{const form=new window.FormData(formElement);const response=await fetch(`/api/admin/recruitment/campaigns/${selectedId}/form`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'interview',prompt:form.get('prompt'),guide:form.get('guide'),maxScore:Number(form.get('maxScore')),sortOrder:data?.interviews.length??0})});const result=await response.json();if(!response.ok)throw new Error(result.error);formElement.reset();await load();}catch(error){setMessage(error instanceof Error?error.message:'면접 문항 생성에 실패했습니다.');}finally{setBusy(false);}}
  async function remove(kind:string,itemId:string){if(!confirm('이 문항을 삭제할까요?'))return;const response=await fetch(`/api/admin/recruitment/campaigns/${selectedId}/form?kind=${kind}&itemId=${itemId}`,{method:'DELETE'});const result=await response.json();if(response.ok)await load();else setMessage(result.error);}
  async function changeStatus(status:string){if(status==='open'&&!confirm('모집을 시작하면 질문을 수정할 수 없습니다. 계속할까요?'))return;setBusy(true);setMessage('');try{const response=await fetch('/api/admin/recruitment/campaigns',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaignId:selectedId,status})});const result=await response.json();if(!response.ok)throw new Error(result.error);setCampaigns(campaigns.map(c=>c.id===selectedId?{...c,status}:c));await load();}catch(error){setMessage(error instanceof Error?error.message:'모집 상태 변경에 실패했습니다.');}finally{setBusy(false);}}
  async function saveEvaluators(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;setBusy(true);setMessage('');try{const form=new window.FormData(formElement);const memberIds=admins.filter(admin=>form.get(`evaluator-${admin.id}`)==='on').map(admin=>admin.id);const response=await fetch(`/api/admin/recruitment/campaigns/${selectedId}/evaluators`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberIds})});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage('평가 관리자를 저장했습니다.');await load();}catch(error){setMessage(error instanceof Error?error.message:'평가 관리자 지정에 실패했습니다.');}finally{setBusy(false);}}
  async function saveSchedule(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new window.FormData(event.currentTarget);setBusy(true);setMessage('');try{const response=await fetch('/api/admin/recruitment/campaigns',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaignId:selectedId,openAt:new Date(String(form.get('openAt'))).toISOString(),closeAt:new Date(String(form.get('closeAt'))).toISOString()})});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage('접수 기간을 저장했습니다.');await load();}catch(error){setMessage(error instanceof Error?error.message:'접수 기간 저장에 실패했습니다.');}finally{setBusy(false);}}

  return <div className="space-y-8">
    {message && <p role="alert" className="rounded-xl bg-monolith-error-container p-4 text-sm font-bold">{message}</p>}
    <section className="rounded-xl bg-monolith-surface-low p-5"><h2 className="text-xl font-black">새 모집 기수</h2><form onSubmit={createCampaign} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input className={field} name="title" placeholder="2026 하반기 모집" required/><input className={field} name="cohort" type="number" min="1" placeholder="기수" required/><label className="text-xs font-bold">접수 시작<input className={`${field} mt-1`} name="openAt" type="datetime-local" required/></label><label className="text-xs font-bold">접수 마감<input className={`${field} mt-1`} name="closeAt" type="datetime-local" required/></label><button disabled={busy} className="min-h-11 self-end rounded-lg bg-monolith-primary px-4 text-sm font-bold text-white"><Plus className="mr-2 inline h-4 w-4"/>기수 생성</button></form></section>
    <section><div className="flex flex-wrap items-center justify-between gap-3"><select className={`${field} max-w-md`} value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">모집을 선택하세요</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.cohort}기 · {c.title} ({statusLabel[c.status]})</option>)}</select>{data&&<div className="flex gap-2">{data.campaign.status==='draft'&&<button disabled={busy} onClick={()=>changeStatus('open')} className="min-h-11 rounded-lg bg-monolith-primary px-4 text-sm font-bold text-white">모집 시작</button>}{data.campaign.status==='open'&&<button disabled={busy} onClick={()=>changeStatus('closed')} className="min-h-11 rounded-lg bg-monolith-surface-container px-4 text-sm font-bold">접수 마감</button>}</div>}</div></section>
    {data && <><section className="rounded-xl border border-monolith-outline-variant p-5"><h2 className="text-2xl font-black">접수 기간</h2><p className="mt-2 text-sm text-monolith-on-surface-muted">선택한 기수의 접수 시작과 마감 시간입니다. 현재 지역 시간을 기준으로 표시됩니다.</p><form key={`schedule-${selectedId}-${data.campaign.application_open_at}`} onSubmit={saveSchedule} className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">접수 시작<input className={`${field} mt-1`} name="openAt" type="datetime-local" defaultValue={toLocalDateTime(data.campaign.application_open_at)} required/></label><label className="text-xs font-bold">접수 마감<input className={`${field} mt-1`} name="closeAt" type="datetime-local" defaultValue={toLocalDateTime(data.campaign.application_close_at)} required/></label><button disabled={busy} className="min-h-11 rounded-lg bg-monolith-primary px-4 text-sm font-bold text-white sm:col-span-2">접수 기간 저장</button></form></section><section className="rounded-xl border border-monolith-outline-variant p-5"><h2 className="text-2xl font-black">평가 관리자</h2><p className="mt-2 text-sm text-monolith-on-surface-muted">지정된 모든 관리자가 모든 지원자를 평가해야 최종 점수가 확정됩니다.</p><form key={selectedId} onSubmit={saveEvaluators} className="mt-5 grid gap-3 sm:grid-cols-2">{admins.map(admin=><label key={admin.id} className="flex min-h-11 items-center gap-3 rounded-lg bg-monolith-surface-low px-4 text-sm"><input type="checkbox" name={`evaluator-${admin.id}`} defaultChecked={data.evaluatorIds.includes(admin.id)} disabled={data.campaign.status!=='draft'}/><span><strong>{admin.name}</strong> · {admin.cohort}기 · {admin.affiliation==='development'?'개발팀':'비즈니스팀'}</span></label>)}{data.campaign.status==='draft'&&<button disabled={busy} className="min-h-11 rounded-lg bg-monolith-primary px-4 text-sm font-bold text-white sm:col-span-2">평가 관리자 저장</button>}</form></section><section><h2 className="text-2xl font-black">지원서 문항</h2><div className="mt-4 space-y-3">{data.questions.map((q,index)=><div key={q.id} className="flex items-start justify-between rounded-xl border border-monolith-outline-variant p-5"><div><p className="text-xs font-bold text-monolith-primary">{index+1} · {q.question_type} · {q.scoring_mode} · {q.max_score}점</p><h3 className="mt-2 font-bold">{q.prompt}</h3>{q.application_question_option?.length>0&&<p className="mt-2 text-sm text-monolith-on-surface-muted">{q.application_question_option.sort((a:any,b:any)=>a.sort_order-b.sort_order).map((o:any)=>`${o.label}${q.scoring_mode==='auto'?` (${o.auto_score}점)`:''}`).join(' · ')}</p>}</div>{data.campaign.status==='draft'&&<button onClick={()=>remove('application',q.id)} aria-label="문항 삭제" className="p-2 text-monolith-error"><Trash2 className="h-4 w-4"/></button>}</div>)}</div></section>
    {data.campaign.status==='draft'&&<form onSubmit={addQuestion} className="grid gap-4 rounded-xl bg-monolith-surface-low p-5 md:grid-cols-2"><h3 className="text-xl font-black md:col-span-2">지원서 문항 추가</h3><select className={field} name="type" required><option value="long_text">주관식</option><option value="yes_no">Yes / No</option><option value="single_choice">객관식 단일 선택</option><option value="multiple_choice">객관식 복수 선택</option></select><select className={field} name="scoringMode"><option value="manual">관리자 수동 채점</option><option value="auto">자동 채점</option></select><input className={`${field} md:col-span-2`} name="prompt" placeholder="질문" required/><input className={`${field} md:col-span-2`} name="description" placeholder="질문 설명 (선택)"/><input className={field} name="maxScore" type="number" min="0" step="0.01" placeholder="최대 배점" required/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="required" defaultChecked/>필수 문항</label><input className={field} name="minLength" type="number" min="0" placeholder="주관식 최소 글자 수"/><input className={field} name="maxLength" type="number" min="1" placeholder="주관식 최대 글자 수"/><textarea className={`${field} min-h-28`} name="options" placeholder={'객관식 선택지 (한 줄에 하나)\n예\n아니오'}/><textarea className={`${field} min-h-28`} name="scores" placeholder={'자동 점수 (선택지와 같은 순서)\n10\n0'}/><button disabled={busy} className="min-h-11 rounded-lg bg-monolith-primary px-4 text-sm font-bold text-white md:col-span-2">지원서 문항 추가</button></form>}
    <section><h2 className="text-2xl font-black">면접 평가 문항</h2><div className="mt-4 space-y-3">{data.interviews.map((q,index)=><div key={q.id} className="flex justify-between rounded-xl border border-monolith-outline-variant p-5"><div><p className="text-xs font-bold text-monolith-primary">{index+1} · {q.max_score}점</p><h3 className="mt-2 font-bold">{q.prompt}</h3>{q.evaluation_guide&&<p className="mt-2 text-sm text-monolith-on-surface-muted">{q.evaluation_guide}</p>}</div>{data.campaign.status==='draft'&&<button onClick={()=>remove('interview',q.id)} className="p-2 text-monolith-error"><Trash2 className="h-4 w-4"/></button>}</div>)}</div></section>
    {data.campaign.status==='draft'&&<form onSubmit={addInterview} className="grid gap-4 rounded-xl bg-monolith-surface-low p-5 md:grid-cols-2"><h3 className="text-xl font-black md:col-span-2">면접 문항 추가</h3><input className={`${field} md:col-span-2`} name="prompt" placeholder="면접 평가 문항" required/><input className={field} name="guide" placeholder="평가 기준 (선택)"/><input className={field} name="maxScore" type="number" min="0" step="0.01" placeholder="최대 배점" required/><button disabled={busy} className="min-h-11 rounded-lg bg-monolith-primary px-4 text-sm font-bold text-white md:col-span-2">면접 문항 추가</button></form>}</>}
  </div>;
}
