import { notFound } from 'next/navigation';
import AdminSectionShell from '@/components/admin/AdminSectionShell';
import ApplicantStatusControl from '@/components/recruitment/ApplicantStatusControl';
import DocumentEvaluationForm from '@/components/recruitment/DocumentEvaluationForm';
import EvaluationForm from '@/components/recruitment/EvaluationForm';
import { getApplicantDetail } from '@/lib/recruitment-admin';
import { requireAdminPageAccess } from '@/lib/admin-auth';

export const dynamic = 'force-dynamic';
export default async function ApplicantDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const member = await requireAdminPageAccess(`/admin/recruitment/${id}`); const applicant = await getApplicantDetail(id); if (!applicant) notFound();
  const evaluationsByQuestion = new Map<string, any[]>(); for (const evaluation of applicant.application_question_evaluation ?? []) evaluationsByQuestion.set(evaluation.question_id, [...(evaluationsByQuestion.get(evaluation.question_id) ?? []), evaluation]);
  const interviewByQuestion = new Map<string, any[]>(); for (const evaluation of applicant.application_interview_evaluation ?? []) interviewByQuestion.set(evaluation.interview_question_id, [...(interviewByQuestion.get(evaluation.interview_question_id) ?? []), evaluation]);
  const answers = [...(applicant.application_answer ?? [])].sort((a,b) => (a.application_question?.sort_order ?? 0) - (b.application_question?.sort_order ?? 0));
  const completion = applicant.application_evaluation_completion?.find((item:any)=>item.evaluator_member_id===member.id);
  const isEvaluator = applicant.evaluators?.some((item:any)=>item.member_id===member.id) ?? false;
  const documentItems = answers.map((answer:any)=>{const evaluations=evaluationsByQuestion.get(answer.application_question.id)??[];const own=evaluations.find((evaluation:any)=>evaluation.evaluator_member_id===member.id);const selected=answer.application_answer_option?.map((item:any)=>item.application_question_option?.label).filter(Boolean).join(', ');return{id:answer.application_question.id,prompt:answer.question_snapshot?.prompt??answer.application_question.prompt,maxScore:Number(answer.application_question.max_score),scoringMode:answer.application_question.scoring_mode,answer:answer.answer_text||selected||'응답 없음',autoScore:answer.auto_score==null?null:Number(answer.auto_score),score:own?Number(own.score):undefined,comment:own?.comment??'',evaluations:evaluations.map((evaluation:any)=>({id:evaluation.id,evaluatorName:evaluation.member?.name??'관리자',score:Number(evaluation.score),comment:evaluation.comment}))};});
  const interviewItems = applicant.interviewQuestions.map((question:any)=>{const own=(interviewByQuestion.get(question.id)??[]).find((evaluation:any)=>evaluation.evaluator_member_id===member.id);return{id:question.id,prompt:question.prompt,maxScore:Number(question.max_score),score:own?Number(own.score):undefined,comment:own?.comment??''};});
  return <AdminSectionShell currentPath="/admin/recruitment" title={`${applicant.name} 지원서`} description={`${applicant.university} ${applicant.major} · ${applicant.recruitment_track?.label ?? '-'}`}>
    <div className="flex flex-col gap-4 rounded-xl bg-monolith-surface-low p-5 sm:flex-row sm:items-center sm:justify-between"><div className="text-sm leading-7"><strong>{applicant.email}</strong><br /><span className="text-monolith-on-surface-muted">{applicant.phone} · {applicant.birth_year}년생</span></div><ApplicantStatusControl applicationId={applicant.id} initialStatus={applicant.status} /></div>
    <section className="mt-8 rounded-xl border border-monolith-outline-variant p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">평가 진행 현황</h2><p className="mt-2 text-sm text-monolith-on-surface-muted">미완료 평가자를 확인할 수 있습니다.</p></div><p className="text-xs font-bold text-monolith-on-surface-muted">총 {applicant.evaluators.length}명</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{applicant.evaluators.map((evaluator:any)=>{const state=applicant.application_evaluation_completion?.find((item:any)=>item.evaluator_member_id===evaluator.member_id);return <div key={evaluator.member_id} className="rounded-lg bg-monolith-surface-low p-4"><p className="text-sm font-bold">{evaluator.member?.name??'관리자'}</p><div className="mt-2 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${state?.document_completed_at?'bg-monolith-primary-fixed text-monolith-primary':'bg-monolith-error-container text-monolith-on-surface'}`}>서류 {state?.document_completed_at?'완료':'미완료'}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${state?.interview_completed_at?'bg-monolith-primary-fixed text-monolith-primary':'bg-monolith-error-container text-monolith-on-surface'}`}>면접 {state?.interview_completed_at?'완료':'미완료'}</span></div></div>;})}</div></section>
    <DocumentEvaluationForm applicationId={applicant.id} items={documentItems} completed={Boolean(completion?.document_completed_at)} globallyFinalized={Boolean(applicant.document_score_finalized_at)} isEvaluator={isEvaluator}/>
    <div className="mt-10"><EvaluationForm applicationId={applicant.id} kind="interview" items={interviewItems} completed={Boolean(completion?.interview_completed_at)} globallyFinalized={Boolean(applicant.interview_score_finalized_at)} isEvaluator={isEvaluator}/></div><div className="mt-10 space-y-6"><h2 className="text-2xl font-black">전체 면접 평가</h2>{applicant.interviewQuestions.map((question:any, index:number) => { const evaluations = interviewByQuestion.get(question.id) ?? []; return <section key={question.id} className="rounded-xl border border-monolith-outline-variant p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-monolith-primary">Interview {index + 1} · {question.max_score}점</p><h3 className="mt-3 text-lg font-black">{question.prompt}</h3>{question.evaluation_guide && <p className="mt-2 text-sm text-monolith-on-surface-muted">{question.evaluation_guide}</p>}{evaluations.length ? evaluations.map((evaluation:any) => <p key={evaluation.id} className="mt-4 text-sm"><strong>{evaluation.member?.name ?? '관리자'} · {evaluation.score}점</strong>{evaluation.comment && <span className="ml-2 text-monolith-on-surface-muted">{evaluation.comment}</span>}</p>) : <p className="mt-4 text-sm text-monolith-on-surface-muted">아직 평가가 없습니다.</p>}</section>; })}</div>
  </AdminSectionShell>;
}
