import { notFound } from 'next/navigation';
import AdminSectionShell from '@/components/admin/AdminSectionShell';
import ApplicantStatusControl from '@/components/recruitment/ApplicantStatusControl';
import EvaluationForm from '@/components/recruitment/EvaluationForm';
import { getApplicantDetail } from '@/lib/recruitment-admin';
import { requireAdminPageAccess } from '@/lib/admin-auth';

export const dynamic = 'force-dynamic';
export default async function ApplicantDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const member = await requireAdminPageAccess(`/admin/recruitment/${id}`); const applicant = await getApplicantDetail(id); if (!applicant) notFound();
  const evaluationsByQuestion = new Map<string, any[]>(); for (const evaluation of applicant.application_question_evaluation ?? []) evaluationsByQuestion.set(evaluation.question_id, [...(evaluationsByQuestion.get(evaluation.question_id) ?? []), evaluation]);
  const interviewByQuestion = new Map<string, any[]>(); for (const evaluation of applicant.application_interview_evaluation ?? []) interviewByQuestion.set(evaluation.interview_question_id, [...(interviewByQuestion.get(evaluation.interview_question_id) ?? []), evaluation]);
  const answers = [...(applicant.application_answer ?? [])].sort((a,b) => (a.application_question?.sort_order ?? 0) - (b.application_question?.sort_order ?? 0));
  const completion = applicant.application_evaluation_completion?.find((item:any)=>item.evaluator_member_id===member.id);
  const isEvaluator = applicant.evaluators?.some((item:any)=>item.member_id===member.id) ?? false;
  const documentItems = answers.filter((answer:any)=>answer.application_question.scoring_mode==='manual').map((answer:any)=>{const own=(evaluationsByQuestion.get(answer.application_question.id)??[]).find((evaluation:any)=>evaluation.evaluator_member_id===member.id);return{id:answer.application_question.id,prompt:answer.application_question.prompt,maxScore:Number(answer.application_question.max_score),score:own?Number(own.score):undefined,comment:own?.comment??''};});
  const interviewItems = applicant.interviewQuestions.map((question:any)=>{const own=(interviewByQuestion.get(question.id)??[]).find((evaluation:any)=>evaluation.evaluator_member_id===member.id);return{id:question.id,prompt:question.prompt,maxScore:Number(question.max_score),score:own?Number(own.score):undefined,comment:own?.comment??''};});
  return <AdminSectionShell currentPath="/admin/recruitment" title={`${applicant.name} 지원서`} description={`${applicant.university} ${applicant.major} · ${applicant.recruitment_track?.label ?? '-'}`}>
    <div className="flex flex-col gap-4 rounded-xl bg-monolith-surface-low p-5 sm:flex-row sm:items-center sm:justify-between"><div className="text-sm leading-7"><strong>{applicant.email}</strong><br /><span className="text-monolith-on-surface-muted">{applicant.phone} · {applicant.birth_year}년생</span></div><ApplicantStatusControl applicationId={applicant.id} initialStatus={applicant.status} /></div>
    <div className="mt-8"><EvaluationForm applicationId={applicant.id} kind="document" items={documentItems} completed={Boolean(completion?.document_completed_at)} globallyFinalized={Boolean(applicant.document_score_finalized_at)} isEvaluator={isEvaluator}/></div>
    <div className="mt-8 space-y-6"><h2 className="text-2xl font-black">지원서 답변</h2>{answers.map((answer:any, index:number) => { const evaluations = evaluationsByQuestion.get(answer.application_question.id) ?? []; const selected = answer.application_answer_option?.map((item:any) => item.application_question_option?.label).filter(Boolean).join(', '); return <section key={answer.id} className="rounded-xl border border-monolith-outline-variant p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-monolith-primary">Question {index + 1} · {answer.application_question.max_score}점</p><h3 className="mt-3 text-lg font-black leading-7">{answer.question_snapshot?.prompt ?? answer.application_question.prompt}</h3><div className="mt-4 whitespace-pre-wrap rounded-lg bg-monolith-surface-low p-4 text-sm leading-7">{answer.answer_text || selected || '응답 없음'}</div>{answer.auto_score != null && <p className="mt-3 text-sm font-bold">자동 점수: {answer.auto_score}점</p>}<div className="mt-5 border-t border-monolith-outline-variant pt-4"><p className="text-sm font-bold">관리자 평가</p>{evaluations.length ? evaluations.map((evaluation:any) => <p key={evaluation.id} className="mt-2 text-sm"><strong>{evaluation.member?.name ?? '관리자'} · {evaluation.score}점</strong>{evaluation.comment && <span className="ml-2 text-monolith-on-surface-muted">{evaluation.comment}</span>}</p>) : <p className="mt-2 text-sm text-monolith-on-surface-muted">아직 평가가 없습니다.</p>}</div></section>; })}</div>
    <div className="mt-10"><EvaluationForm applicationId={applicant.id} kind="interview" items={interviewItems} completed={Boolean(completion?.interview_completed_at)} globallyFinalized={Boolean(applicant.interview_score_finalized_at)} isEvaluator={isEvaluator}/></div><div className="mt-10 space-y-6"><h2 className="text-2xl font-black">전체 면접 평가</h2>{applicant.interviewQuestions.map((question:any, index:number) => { const evaluations = interviewByQuestion.get(question.id) ?? []; return <section key={question.id} className="rounded-xl border border-monolith-outline-variant p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-monolith-primary">Interview {index + 1} · {question.max_score}점</p><h3 className="mt-3 text-lg font-black">{question.prompt}</h3>{question.evaluation_guide && <p className="mt-2 text-sm text-monolith-on-surface-muted">{question.evaluation_guide}</p>}{evaluations.length ? evaluations.map((evaluation:any) => <p key={evaluation.id} className="mt-4 text-sm"><strong>{evaluation.member?.name ?? '관리자'} · {evaluation.score}점</strong>{evaluation.comment && <span className="ml-2 text-monolith-on-surface-muted">{evaluation.comment}</span>}</p>) : <p className="mt-4 text-sm text-monolith-on-surface-muted">아직 평가가 없습니다.</p>}</section>; })}</div>
  </AdminSectionShell>;
}
